# Generated by Django 4.2.7 on 2026-04-11 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbf_id', models.IntegerField(help_text='TBF faaliyetId', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age_group', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('season', models.CharField(default='2025-2026', max_length=20)),
                ('season_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lig',
                'verbose_name_plural': 'Ligler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hakem', 'Hakem'), ('masa_gorevlisi', 'Masa Gorevlisi'), ('gozlemci', 'Gozlemci'), ('atama_sorumlusu', 'Atama Sorumlusu'), ('il_temsilcisi', 'Il Temsilcisi')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active_official', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanici Profili',
                'verbose_name_plural': 'Kullanici Profilleri',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbf_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.league')),
            ],
            options={
                'verbose_name': 'Takim',
                'verbose_name_plural': 'Takimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbf_match_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('match_code', models.CharField(blank=True, max_length=20)),
                ('home_team_name', models.CharField(max_length=200)),
                ('away_team_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('week', models.CharField(blank=True, max_length=50)),
                ('round_info', models.CharField(blank=True, help_text='Yari Final, Final vb.', max_length=100)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('is_played', models.BooleanField(default=False)),
                ('match_status_id', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='core.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.league')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venue')),
            ],
            options={
                'verbose_name': 'Mac',
                'verbose_name_plural': 'Maclar',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_referee_assignments', to='core.userprofile', verbose_name='Yardimci Hakem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('head_referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_referee_assignments', to='core.userprofile', verbose_name='Bas Hakem')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.match')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observer_assignments', to='core.userprofile', verbose_name='Gozlemci')),
                ('scorer_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorer1_assignments', to='core.userprofile', verbose_name='Sayi Gorevlisi 1')),
                ('scorer_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorer2_assignments', to='core.userprofile', verbose_name='Sayi Gorevlisi 2')),
                ('shot_clock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_clock_assignments', to='core.userprofile', verbose_name='Sut Saati Gorevlisi')),
                ('timer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_assignments', to='core.userprofile', verbose_name='Sure Gorevlisi')),
            ],
            options={
                'verbose_name': 'Atama',
                'verbose_name_plural': 'Atamalar',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Musaitlik',
                'verbose_name_plural': 'Musaitlikler',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
