# Generated by Django 4.2.7 on 2026-04-13 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Baslik')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('start_date', models.DateField(verbose_name='Baslangic Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitis Tarihi')),
                ('target_roles', models.CharField(default='hakem,masa_gorevlisi,gozlemci', help_text='Virgul ile ayrilmis roller: hakem,masa_gorevlisi,gozlemci', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Son Bildirim Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musaitlik Istegi',
                'verbose_name_plural': 'Musaitlik Istekleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
