# Generated by Django 4.2.7 on 2026-04-13 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_availabilityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classification',
            field=models.CharField(blank=True, choices=[('A', 'A Klasman'), ('B', 'B Klasman'), ('C', 'C Klasman'), ('il', 'Il Hakemi'), ('aday', 'Aday Hakem'), ('', 'Belirsiz')], help_text='Sadece hakemler icin gecerlidir', max_length=10, verbose_name='Klasman'),
        ),
        migrations.CreateModel(
            name='AssignmentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Baslik')),
                ('start_datetime', models.DateTimeField(verbose_name='Acilis Zamani')),
                ('end_datetime', models.DateTimeField(verbose_name='Kapanis Zamani')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atama Penceresi',
                'verbose_name_plural': 'Atama Pencereleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
