# Generated by Django 4.2.7 on 2026-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_league_category_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='category',
            field=models.CharField(choices=[('a_ligi', 'A Ligi'), ('b_ligi', 'B Ligi'), ('gencler', 'Gencler'), ('kucukler', 'Kucukler'), ('diger', 'Diger')], default='diger', help_text='A Ligi, B Ligi gibi kategoriler icin kullanilir', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitis Tarihi'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Baslangic Tarihi'),
        ),
    ]
