# Generated by Django 4.2.7 on 2026-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tournament_dates_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrequest',
            name='specific_dates',
            field=models.TextField(blank=True, help_text='Virgul ile ayrilmis ISO tarihler: 2026-04-03,2026-04-06', verbose_name='Secilen Gunler'),
        ),
        migrations.AlterField(
            model_name='availabilityrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitis Tarihi'),
        ),
        migrations.AlterField(
            model_name='availabilityrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Baslangic Tarihi'),
        ),
        migrations.AlterField(
            model_name='availabilityrequest',
            name='target_roles',
            field=models.CharField(default='hakem,masa_gorevlisi,gozlemci', help_text='Virgul ile ayrilmis roller', max_length=100),
        ),
    ]
